### ISSUE TITLE
Defining general intelligence

### ISSUE THREAD

**Issue by razvan-panda** [fairy-tale-agi-solutions/fairy-tale-artificial-general-intelligence-solutions#12]
We need a definition that is as clear as possible in explaining what general intelligence is.

Bonus points if we can get it formalized.

**Comment by razvan-panda** [comment]
[A Collection of Definitions of Intelligence](https://arxiv.org/abs/0706.3639)
[A Formal Measure of Machine Intelligence](https://arxiv.org/abs/cs/0605024)
[Universal Intelligence: A Definition of Machine Intelligence](https://arxiv.org/abs/0712.3329)

**Comment by razvan-panda** [comment]
This is - I hope - a decent understanding of what general intelligence means to me:

General intelligence is a metric - let's say one dimensional for now
It measures how good a system is at achieving any possible goal under any context - by convention the higher the value of the metric the better the system is at performing actions which would allow it to achieve any goal under any context
A system is a spatial slice of the universe
A goal is any constraint/convergence on the possible futures
A context means that the system could be put in any possible environment
Environment would be everything outside of the system - the rest of the world

^ How full reality determinism would interfere with this should be accounted for

**Comment by puffnfresh** [comment]
```haskell
data Perception observation reward
  = Perception observation reward

data Agent observation reward action
  = Agent (Perception observation reward -> action)

data Environment observation reward action
  = Environment (action -> Perception observation reward)
```

**Comment by logicmoo** [comment]
In defining general intelligence this does not require the demonstrator (the AGI) to be consciousness.  But if it was conscious, what that make it easier or harder to make it demonstratable?

**Comment by razvan-panda** [comment]
I guess we would need a formal definition of consciousness for that - no idea how to get close to that.

Consciousness appears to be some brain behavior which is symbolic in nature and acting similarly to the way leaders in society act - it iterates over other brain modules and optimizes them.

Consciousness actually seems to be the highest point of change from power / general intelligence point of view - the actions taken by consciousness have the biggest effects than any other system in a body.

**Comment by logicmoo** [comment]
When starting to write a definition I realized I meant "self" 

> Consciousness  appears to be some brain behavior which is symbolic in nature and acting...

So my definition of consciousness is:  

The integration of the mind's eye, ears, nose into a becoming a "thing" that advocates for one's self as if it   was oneself.

**Comment by razvan-panda** [comment]
I don't get this part: `a "thing" that advocates for one's self as if it was oneself`.
Does advocate mean `to make decisions`?
The integration bit is in systems theory like the simplest diagram of a system:

![](http://images.lesswrong.com/t3_mxb_0.png)

Where inputs are all of the senses including self-awareness type senses and the output are decisions/actions/effects performed on the environment.

**Comment by logicmoo** [comment]
When starting to write a definition I realized I meant "self" 

> Consciousness appears to be some brain behavior which is symbolic in nature and acting...

So my definition of consciousness is:  

The integration of the mind's eye, ears, nose (all senses and feelings)  into a becoming a "thing" that advocates for one's self as if it was oneself. 

>  and acting similarly to the way leaders in society act 

Yes, consciousness is a delegator force (rather than an actor force) making societies sometimes think of its leader as a good for nothing busybody that doesn't do anything other them forcing others to act in its own interest. (that actually ends up being close to whats needed)  Though most AGI theories believe this leadership can somehow emerge.  Seems "practical"

>  it iterates over other brain modules and optimizes them.

Yes, it looks at things from a certain perspective that is optimizing them. From a higher perspective, it does optimize them by giving cohesion to the herd of cats.  

This sounds good, right?   Well think of it this way, your mother asks you to wash the dishes.  It normally takes you about 10 minutes total.  But tonight what happens when she stays and lords over your every dish asking "do you really think it is clean?" "Why don't you wash the plates before the utensils?" "Why are you going so slow?"  "Why do you have to dry every dish immediately instead of letting them sit in the dish drainer?" "If you didn't spend all this time being defensive, you'd get done faster!".   That night it takes you twice as long and you do not get as much time doing other beneficial things.  But this is what consciousness does.   Most AGI theory implementations will optimize themselves so that consciousness will not emerge.  Why I asked the question is *I* that indeed as a hindrance to "demonstration"   :)

**Comment by razvan-panda** [comment]
One thing that I am highly certain is required for defining general intelligence is that the system needs to have a simplified model of reality.

The simplified model of reality the system has inside it allows it to predict the future based on what actions it would take.

**Comment by razvan-panda** [comment]
Are there any AGI implementations that are attempting to work the same way society works?
Society seems to work similar to the way the human brain works - our leaders being like closer to being global consciousness. The higher leaders input and output - power (change over time) effects the more he would be a global consciousness point of society.

And society itself is like a super GI because it is an aggregation of GIs. It is quite likely that the basic way society works is analogous to the way the human brains work.

**Comment by chophshiy** [comment]
A working definition that could obviously use some cleaning up:

Artificial: means that the biases and capabilities inherited by the entity/product originate (intentionally or unwittingly) from the choices/actions of other agents (rather than from evolution).

General: means the same thing as when we refer to a general purpose computer;  Given sufficient resources (inherited or acquired) it can engage any ‘problem’/challenge. {Though a general purpose computer/agent may require an impractical amount of resources to achieve its goal/output (time, memory, etc.).}

Intelligence: is a composite fitness metric.  As with biological fitness, its evaluation requires that we specify both an agent/organism and an environment.  {What is intelligent/fit (of a specified organism/agent) in one environment is not so in another.}

Given a set of inherent biases, the entity values some outcomes/stimuli positively and some negatively.  {Describing an intelligence = describing a thing with goals.}

Given a set of environmental conditions, the present context implies some positive and/or negative outcomes.  {Set of entities/events causally implies specific progression/outcomes}

Recognition (inherited or acquired retention and recall) of these potentials acts to select the greatest value gradients (attractive or repulsive) = the present goal/priority set (attention).  {Selection of present goal(s) which complements/fits the present scenario (environment conditions)}  

Some primary goal(s) are more beneficial that others given a particular scenario.  {Generalized intelligence is coordinated/fit goal selection which can span all conceivable scenarios (solutions may be counterfactual (‘if I could fly’ may easily be a valid tactic which would result in success, so airplanes get invented))}

Selection of actions/behaviors then has its own fitness;  A selected sub-goal/tactic may be within the (believed) capabilities of the entity (accessible) and toward the more-desirable outcome (convergent), and more or less efficient/effective (error/reward value).  

Intention (volition) is always toward an improved outcome, when compared to alternate outcomes in which the entity interceded otherwise, or failed/elected-not-to intercede.  An agent which cannot intercede in the progression of its reality is not, by this definition, to be considered 'intelligent' (which is the intuitive motivator behind the 'embodiment' movement).

**Comment by chophshiy** [comment]
The aspects which are described separately above are in fact implemented by a single process type.

**Comment by razvan-panda** [comment]
@chophshiy When ready send a merge request for it so we can natural language/code review it
